#!/usr/bin/env ruby
# frozen_string_literal: true

require "eclair"
require "eclair/grid"

Eclair.init_config
Curses.init_screen
Curses.stdscr.timeout = 100
Curses.stdscr.keypad = true
Curses.start_color
Curses.use_default_colors
Curses.crmode
Curses.noecho
Curses.curs_set(0)
trap("INT") { exit }

grid = Eclair::Grid.new

loop do
  case k = Curses.stdscr.getch
  when Curses::KEY_RESIZE
    grid.resize
  when Curses::KEY_LEFT, Curses::KEY_RIGHT, Curses::KEY_UP, Curses::KEY_DOWN
    grid.move(k)
  when " "
    grid.space
  when 10
    grid.action
  end
end
